### ISSUE TITLE
Support for latest OMNET++ & INET frameworks

### ISSUE THREAD

**Issue by beLizzard1** [w-wallner/libPTP#3]
Very much appreciate what you have done here but it is unfortunate that it currently doesn't work with more recent versions of the toolkits.

Given that I need later versions for the work I am doing, I have been trying to update this to the latest versions.

Thus far, introducing namespaces to your code addresses many of the initial 'visible' issues my difficulties. I've been having issues getting this project to even compile the code. 

As the original developer of the code, you might have more of an insight into what needs to change and have some advice on how to compile it.

**Comment by w-wallner** [comment]
Hi,
the project was unmaintained for the last couple of years. Recently there is activity again. The code has meanwhile moved to [https://github.com/ptp-sim/libPTP](https://github.com/ptp-sim/libPTP).

The new website is at [https://ptp-sim.github.io/](https://ptp-sim.github.io/).
The community forum is located at [http://ptp-sim.boards.net/](http://ptp-sim.boards.net/).

How far have you come with porting to newer OMNeT++ versions?
If you would still be interested in contributing, please join our discussions in the forum mentioned above.

I will close the issue here, we have it on the agenda anyway.
